---
- hosts: localhost
  gather_facts: false
  vars_files:
    - secrets/vault.yaml

  tasks:
    - name: Show all loaded variables
      debug:
        var: vars

    - name: Fail if db_credentials is missing
      fail:
        msg: "db_credentials is missing"
      when: db_credentials is not defined

    - name: Base64 encode secrets and create k8s secret manifest content
      set_fact:
        k8s_secret_data: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: attendance-service-secret
            namespace: qr-attendance
          type: Opaque
          data:
            SPRING_DATASOURCE_USERNAME: "{{ db_credentials.username | b64encode }}"
            SPRING_DATASOURCE_PASSWORD: "{{ db_credentials.password | b64encode }}"

    - name: Write the k8s secret manifest to file
      copy:
        content: "{{ k8s_secret_data }}"
        dest: k8s/secrets/secrets.yaml

    - name: Show all vars
      debug:
        var: vars
