apiVersion: v1
kind: Secret
metadata:
  name: attendance-service-secret
  namespace: qr-attendance
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: "anVoaXJhamFuaQ=="
  SPRING_DATASOURCE_PASSWORD: "anVoaTEyMw=="
