apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: qr-attendance
spec:
  type: NodePort  # You can change this to LoadBalancer if using cloud or Ingress later
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000  # Optional, pick available port between 30000–32767
