apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance-service
  namespace: spe-final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendance-service
  template:
    metadata:
      labels:
        app: attendance-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo "Waiting for Postgres..."; sleep 5; done']
        - name: wait-for-eureka
          image: busybox
          command: ['sh', '-c', 'until nc -z server-registry 8761; do echo "Waiting for Eureka..."; sleep 5; done']
        - name: wait-for-face
          image: busybox
          command: ['sh', '-c', 'until nc -z face-recognition-service 5001; do echo "Waiting for Face Recognition..."; sleep 5; done']
        - name: fix-permissions
          image: busybox
          command: [ "sh", "-c", "chmod -R 777 /app/images" ]
          volumeMounts:
            - name: images-volume
              mountPath: /app/images
      containers:
        - name: attendance-service
          image: juhir10/attendance-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/attendance
            - name: SPRING_DATASOURCE_USERNAME
              value: juhirajani
            - name: SPRING_DATASOURCE_PASSWORD
              value: juhi123
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://server-registry:8761/eureka
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 150
            periodSeconds: 20
            failureThreshold: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: images-volume
              mountPath: /app/images
      volumes:
        - name: images-volume
          persistentVolumeClaim:
            claimName: shared-pvc

