apiVersion: v1
kind: Service
metadata:
  name: attendance-service
  namespace: qr-attendance
spec:
  selector:
    app: attendance-service
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
