apiVersion: v1
kind: Service
metadata:
  name: attendance-service
  namespace: spe-final
spec:
  selector:
    app: attendance-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
