apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-recognition-service
  namespace: spe-final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: face-recognition-service
  template:
    metadata:
      labels:
        app: face-recognition-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z postgres-service 5432; do
                echo "Waiting for Postgres..."
                sleep 5
              done
        - name: wait-for-eureka-service
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z server-registry 8761; do
                echo "Waiting for Eureka..."
                sleep 5
              done
        - name: fix-permissions
          image: busybox
          command: [ "sh", "-c", "chmod -R 777 /app/images" ]
          volumeMounts:
            - name: images-volume
              mountPath: /app/images
      containers:
        - name: face-container-service
          image: juhir10/face-recognition-service:latest
          ports:
            - containerPort: 5001
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 5
          env:
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_PORT
              value: "5432"
            - name: SERVER_REGISTRY_HOST
              value: server-registry
            - name: SERVER_REGISTRY_PORT
              value: "8761"
          volumeMounts:
            - name: images-volume
              mountPath: /app/images
      volumes:
        - name: images-volume
          persistentVolumeClaim:
            claimName: shared-pvc






