apiVersion: v1
kind: Service
metadata:
  name: face-recognition-service
  namespace: qr-attendance
spec:
  selector:
    app: face-recognition-service
  type: ClusterIP
  ports:
    - port: 5001
      targetPort: 5001