#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: postgres-deployment
#  namespace: spe-final
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: postgres
#  template:
#    metadata:
#      labels:
#        app: postgres
#    spec:
#      containers:
#        - name: postgres-container
#          image: postgres:13
#          ports:
#            - containerPort: 5432
#          env:
#            - name: POSTGRES_DB
#              value: attendance
#            - name: POSTGRES_USER
#              value: juhirajani
#            - name: POSTGRES_PASSWORD
#              value: juhi123
#          livenessProbe:
#            exec:
#              command: ["pg_isready", "-U", "juhirajani", "-d", "attendance"]
#            initialDelaySeconds: 30
#            periodSeconds: 10
#            timeoutSeconds: 5
#            failureThreshold: 5
#          readinessProbe:
#            exec:
#              command: ["pg_isready", "-U", "juhirajani", "-d", "attendance"]
#            initialDelaySeconds: 10
#            periodSeconds: 10
#            timeoutSeconds: 5
#            failureThreshold: 5


apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: spe-final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres-container
          image: postgres:13
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "juhirajani", "-d", "attendance"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "juhirajani", "-d", "attendance"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

