apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: qr-attendance
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=       # base64 for "postgres"
  POSTGRES_PASSWORD: anVoaXJhamFuaQ==   # base64 for "password"
  POSTGRES_DB: anVoaTEyMw==    # base64 for "attendance"
