#apiVersion: v1
#kind: Service
#metadata:
#  name: postgres
#  namespace: qr-attendance
#spec:
#  selector:
#    app: postgres
#  ports:
#    - protocol: TCP
#      port: 5432
#      targetPort: 5432
#  type: ClusterIP

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: spe-final
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
