apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: qr-code-attendance-hpa
  namespace: spe-final
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qr-code-attendance
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60