apiVersion: v1
kind: Service
metadata:
  name: qr-code-attendance
  namespace: qr-attendance
spec:
  selector:
    app: qr-code-attendance
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082