apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: eureka-server-hpa
  namespace: spe-final
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eureka-server-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70