apiVersion: v1
kind: Service
metadata:
  name: server-registry-service
  namespace: qr-attendance
spec:
  selector:
    app: server-registry
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: ClusterIP

